library(tidyverse)
library(ggpcp)
library(gridExtra)

theme_set(theme_bw())

library(scales)

oranges <- c("#FDBF6F", "#F89D38", "#F37A00")
purples <- c("#CAB2D6", "#9A78B8", "#6A3D9A")
greens <- c("#b2df8a", "#73C05B", "#33a02c")

cols <-  c(oranges[2], greens[2], purples[2])

library(palmerpenguins)

penguins1 <- penguins_raw
penguins1 <- penguins1 %>%
  separate(col = `Individual ID`, into = c("Nest", "Individ"),
           remove = FALSE, sep = -2)
names(penguins1)[12:15] <- c("CulmenL", "CulmenD", "FlipperL", "BodyMass")
penguins1 <- penguins1 %>%
  separate(Species, into = c("species", "foo2", "foo3", "foo4"), sep = " ") %>%
  select(-starts_with("foo"))
# foos make R happy, because it doesn't throw away anything unexpected

df <- penguins
df_pcp <- df %>%
  pcp_select(bill_length_mm:body_mass_g) %>%
  pcp_scale()

df_pcp$Observation <- paste0("Penguin #", df_pcp$pcp_id, " (", df_pcp$species, ")")
df_pcp$Observation <- paste0("Penguin #", df_pcp$pcp_id)

df_pcp %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp(aes(colour = Observation),
    size = 1,
    data = df_pcp %>% filter(pcp_id %in% c(1, 275))
  ) +
  geom_point(aes(shape = Observation, colour = Observation),
    size = 5,
    data = df_pcp %>% filter(pcp_id %in% c(1, 275))
  ) +
  theme_bw() +
  xlab("") +
  scale_colour_manual("Observation", values = c("darkorange", "purple4")) +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  scale_x_discrete(
    expand = expansion(add = 0.2),
    labels = c(
      "Bill Length (mm)", "Bill Depth (mm)",
      "Flipper Length (mm)", "Body Mass (g)"
    )
  )

penguins <- rbind(
  penguins %>% filter(species == "Adelie"),
  penguins %>% filter(species == "Gentoo"),
  penguins %>% filter(species == "Chinstrap")
)

pcp <- penguins %>%                       # data management:
  filter(!is.na(sex)) %>%                 #   tidy workflow
  pcp_select(4,3,5:6, sex, species) %>%   #   var selection (sec 3.1)
  pcp_scale(method="uniminmax") %>%       #   scale values (sec 3.2)
  pcp_arrange() %>%                       #   arrange categ. data
  ggplot(aes_pcp()) +                     # create chart layers:
    geom_pcp_axes() +                     #   vertical lines for axes
    geom_pcp(aes(colour = species),       #   line  segments
            alpha = 0.8, overplot="none") +
    geom_pcp_labels()                     #   label categories

penguins %>%
  filter(!is.na(sex)) %>%
  pcp_select(4, 3, 5:6, sex, species) %>%
  pcp_scale(method = "uniminmax") %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp(aes(colour = species), alpha = 0.8, overplot = "none") +
  geom_pcp_labels() +
  scale_color_manual("Species", values = cols) +
  theme_bw() +
  scale_x_discrete(
    expand = expansion(add = 0.3),
    labels = c(
      "Bill Depth (mm)", "Bill Length (mm)",
      "Flipper Length (mm)", "Body Mass (g)",
      "Sex", "Species"
    )
  ) +
  xlab("") +
  ylab("") +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none")

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=3140R0kllllaFw0g0qFqFg0w0aF


# *** Primary color:
primary <- c("#AA8939", "#FFE7AA", "#D4B66A", "#806115", "#553D00")

# *** Secondary color (1):

secondary <- c("#5A2971", "#9974AA", "#784A8E", "#3F1255", "#270339")

# *** Secondary color (2):

tertiary <- c("#277552", "#75B095", "#499371", "#0F5837", "#003B20")

#####  Generated by Paletton.com (c) 2002-2014

data("olive", package = "tourr")

oils <- olive %>% mutate(
  area = reorder(area, region)
)

dt1 <- oils %>%
  mutate(
    region = factor(region)
  ) %>%
  pcp_select(region, area, palmitic:eicosenoic) %>%
  pcp_scale(method = "uniminmax") %>%
  pcp_arrange(space = 0.2)
dt1$scaling <- "uniminmax"

dt2 <- oils %>%
  mutate(
    region = factor(region)
  ) %>%
  pcp_select(region, area, palmitic:eicosenoic) %>%
  pcp_scale(method = "robust") %>%
  pcp_arrange(space = 0.2)
dt2$scaling <- "robust"

dt <- rbind(dt1, dt2)


oils1 <- dt2 %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp_boxes() +
  geom_pcp(aes(colour = area), alpha = 0.5, overplot = "none") +
  facet_grid(scaling ~ ., labeller = "label_both", scales = "free_y") +
  scale_colour_manual(values = c(primary[c(2, 4, 3, 1)], secondary[1:2], tertiary[1:3])) +
  theme_bw() +
  theme(legend.position = "none") +
  guides(colour = guide_legend(override.aes = list(alpha = 1, size = 2), reverse = TRUE)) +
  scale_x_discrete(expand = expansion(add = 0.3)) +
  scale_y_continuous(
    labels = c("-4 MAD", "-2 MAD", "median", "+2 MAD", "+4 MAD"),
    breaks = seq(-.5, 1.5, by = 0.5)
  ) +
  xlab("") +
  ylab("") +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

oils2 <- dt1 %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp_boxes() +
  geom_pcp(aes(colour = area), alpha = 0.5, overplot = "none") +
  facet_grid(scaling ~ ., labeller = "label_both", scales = "free_y") +
  scale_colour_manual(values = c(primary[c(2, 4, 3, 1)], secondary[1:2], tertiary[1:3])) +
  theme_bw() +
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(override.aes = list(alpha = 1, size = 2), reverse = TRUE)) +
  scale_x_discrete(expand = expansion(add = 0.3)) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  xlab("") +
  ylab("")

library(patchwork)
oils1 / oils2

set.seed(20200924)

df <- penguins %>%
  na.omit() %>%
  group_by(species, sex) %>%
  slice_sample(n = 3, replace = FALSE) %>%
  mutate(id = 1:n())

df <- df %>% filter(
  !(species == "Chinstrap" & sex == "male"),
  !(species == "Adelie" & sex == "male" & id == 3) &
    !(species == "Gentoo" & sex == "female" & id != 1)
)

x1 <- as.numeric(df$sex)
x2 <- as.numeric(df$species)
jitter1 <- runif(n = 12, min = -0.1, max = 0.1)
jitter2 <- runif(n = 12, min = -0.1, max = 0.1)
y <- as.factor(df$species)
dfnew <- tibble(
  v1 = x1, v2 = x2,
  v3 = as.factor(x1),
  v4 = as.factor(x2),
  z = y,
  v5 = x2 + jitter1,
  v6 = x1 + jitter2,
  v7 = c(sample(5), 5 + 10 + sample(3), 18 + 10 + sample(4))
)
dfnew <- dfnew %>% arrange(v1, v7)
dfnew$v8 <- c(sample(7), 20 + sample(5))

dfnew2 <- dfnew %>%
  mutate(z = factor(z, levels = c("Chinstrap", "Adelie", "Gentoo"))) %>%
  mutate(v4 = factor(as.numeric(z)))

p1 <- dfnew %>%
  pcp_select(v1:v2) %>%
  pcp_scale() %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  #  geom_point(colour="darkgrey", size=3, alpha = .6) +
  geom_point(colour = "grey60", fill = "grey60", size = 5, alpha = .1, pch = 15) +
  geom_point(colour = "grey60", size = 5, pch = 0) +
  geom_pcp(aes(colour = z), size = 1) +
  theme_bw() +
  scale_color_manual(values = c(oranges[2], purples[2], greens[2])) +
  xlab("") +
  ylab("") +
  facet_grid(. ~ "Original PCP") +
  theme(
    axis.title.y = element_blank(), axis.text.y = element_blank(),
    axis.ticks.y = element_blank(), legend.position = "none"
  ) +
  scale_x_discrete(expand = expansion(add = 0.15), labels = c("Sex", "Species"))



p2 <- dfnew %>%
  mutate(v1 = v4, v2 = v3) %>%
  pcp_select(v2, v1) %>%
  pcp_scale() %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp_boxes(boxwidth = 0.3, fill = "grey90", alpha = 0.5) +
  geom_pcp_axes() +
  geom_pcp(aes(colour = z), size = 1) +
  theme_bw() +
  scale_color_manual(values = c(oranges[2], purples[2], greens[2])) +
  xlab("") +
  ylab("") +
  facet_grid(. ~ "GPCP style") +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none") +
  ylim(c(0, 1)) +
  scale_x_discrete(expand = expansion(add = 0.2), labels = c("Sex", "Species"))



p3 <- dfnew %>%
  mutate(v1 = v6, v2 = v5) %>%
  pcp_select(v1:v2) %>%
  pcp_scale() %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_point(aes(colour = z), size = 2.5, alpha = .6) +
  geom_pcp(size = 1, aes(colour = z)) +
  theme_bw() +
  ylab("") +
  scale_color_manual(values = c(oranges[2], purples[2], greens[2])) +
  xlab("") +
  facet_grid(. ~ "Jittering") +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none") +
  scale_x_discrete(expand = expansion(add = 0.15), labels = c("Sex", "Species"))

p4 <- dfnew %>%
  pcp_select(v8, v7) %>%
  pcp_scale() %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_point(aes(colour = z), size = 2.5, alpha = .6) +
  geom_pcp(size = 1, aes(colour = z)) +
  theme_bw() +
  ylab("") +
  scale_color_manual(values = c(oranges[2], purples[2], greens[2])) +
  xlab("") +
  facet_grid(. ~ "Equally spaced") +
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none") +
  scale_x_discrete(expand = expansion(add = 0.15), labels = c("Sex", "Species"))

grid.arrange(p1, p3, p4, p2, nrow = 1)

pcp_df <- penguins %>%
  arrange(sex) %>% # NA last = top of PCP axis
  pcp_select(sex, species) %>%
  pcp_scale(method = "uniminmax") %>%
  pcp_arrange()
ggplot(pcp_df, aes_pcp()) + geom_pcp_axes() +
  geom_pcp(aes(colour = species), overplot = "none") +
  geom_pcp_labels() + theme_pcp()

ggplot(pcp_df, aes_pcp()) + geom_pcp_axes() +
  geom_pcp(aes(colour = species), overplot = "small-on-top") +
  geom_pcp_labels() + theme_pcp()


pp1 <- ggplot(pcp_df, aes_pcp()) +
  geom_pcp_axes() +
  # plot the dataset in the provided order
  geom_pcp(aes(colour = species), overplot = "none") +
  geom_pcp_labels() +
  scale_color_manual("Species", values = cols, guide = "none") +
  ggtitle("Overplot = 'none'") +
  theme_pcp()

pp2 <- ggplot(pcp_df, aes_pcp()) +
  geom_pcp_axes() +
  # plot the smallest category (chinstrap) on top
  geom_pcp(aes(colour = species), overplot = "small-on-top") +
  geom_pcp_labels() +
  scale_color_manual("Species", values = cols, guide = "none") +
  ggtitle("Overplot = 'small-on-top'") +
  theme_pcp()

library(patchwork)
pp1 + pp2 + plot_layout(nrow = 1, byrow = FALSE) + theme_pcp()

penguins1 <- penguins1 %>%
  rename(
    `study ID` = studyName, `Bill Length` = CulmenL,
    `Bill Depth` = CulmenD, `Flipper Length` = FlipperL,
    `Body Weight` = BodyMass
  )

# First pcp
pp1 <- penguins1 %>%
  filter(!is.na(Sex)) %>%
  pcp_select(`study ID`, species, Island, `Bill Length`:`Body Weight`) %>%
  pcp_scale() %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes(colour = "white") +
  geom_pcp(aes(colour = species), alpha = 0.6, overplot = "none") +
  geom_pcp_boxes(fill = "white", alpha = 0.5) +
  geom_pcp_labels() +
  theme_bw() +
  xlab(NULL) +
  ylab(NULL) +
  theme(
    axis.text.y = element_blank(), axis.ticks.y = element_blank(),
    legend.position = "none"
  ) +
  ggtitle("Original order of levels and variables") +
  scale_colour_manual(values = cols)

penguins1 <- penguins1 %>%
  mutate(species = factor(species, levels = c("Chinstrap", "Adelie", "Gentoo"))) %>%
  mutate(island = factor(Island, levels = c("Dream", "Torgersen", "Biscoe")))


# Fourth pcp
pp2 <- penguins1 %>%
  filter(!is.na(Sex)) %>%
  pcp_select(`study ID`, species, island, `Bill Length`:`Body Weight`) %>%
  pcp_scale() %>%
  pcp_arrange(method = "from-left") %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp(aes(colour = species), alpha = 0.6, overplot = "none") +
  geom_pcp_boxes(fill = "white", alpha = 0.5) +
  geom_pcp_labels() +
  theme_bw() +
  xlab(NULL) +
  ylab(NULL) +
  theme(
    axis.text.y = element_blank(), axis.ticks.y = element_blank(),
    legend.position = "none"
  ) +
  scale_colour_manual(values = c(cols[2], cols[1], cols[3])) +
  ggtitle("Levels reordered to emphasize relationship between islands and species")

library(patchwork)
pp1 + pp2 + plot_layout(nrow = 2, byrow = FALSE)


# Reorder the variables, moving CulmenL to the right, and do case ordering from the left
# Invert the CulmenD variable (and use the minus notation :-))
penguins1 <- penguins1 %>% mutate(`-Bill Depth` = -`Bill Depth`)


# Change the order of printing the colours to make Chinstrap stand out better
# Requires rearranging of dataset case order and using overplot="none"
penguins1 <- penguins1 %>% arrange(fct_rev(species))

penguins1 %>%
  filter(!is.na(Sex)) %>%
  pcp_select(`study ID`, species, island, `-Bill Depth`, `Flipper Length`, `Body Weight`, `Bill Length`) %>%
  group_by(Sex) %>%
  pcp_scale(.by_group = TRUE) %>%
  pcp_arrange(method = "from-left", .by_group = TRUE) %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp(aes(colour = interaction(Sex, species)), overplot = "none", alpha = 0.8) +
  geom_pcp_boxes(fill = "white", alpha = 0.6) +
  geom_pcp_labels(fill = "white", alpha = 0.6) +
  theme_bw() +
  xlab(NULL) +
  ylab(NULL) +
  theme(
    axis.text.y = element_blank(), axis.ticks.y = element_blank(),
    legend.position = "none"
  ) +
  scale_colour_manual(values = c(greens[c(1, 3)], oranges[c(1, 3)], purples[c(1, 3)])) +
  facet_grid(Sex ~ .)

 penguins <- penguins %>%
   mutate(
     species = factor(species, c("Chinstrap", "Adelie", "Gentoo")),
     species2 = factor(species, c("Adelie", "Gentoo", "Chinstrap")),
     `-bill_length_mm` = -bill_length_mm,
     `-bill_depth_mm` = -bill_depth_mm
   )

 penguins_pcp <- penguins %>%
   mutate(
     sex = ifelse(is.na(sex), "?", as.character(sex)),
     sex = factor(sex, levels = c("female", "?", "male"))
   ) %>%
   filter(!is.na(body_mass_g)) %>%
   pcp_select(
     species2, `bill_length_mm`,
     flipper_length_mm, body_mass_g, `-bill_depth_mm`, species, sex
   ) %>%
   pcp_scale() %>%
   pcp_arrange()

 penguins_pcp %>%
   ggplot(aes_pcp()) +
   geom_pcp_axes() +
   geom_pcp_boxes(boxwidth = 0.1) +
   geom_pcp(aes(colour = sex), alpha = 0.8) +
   geom_pcp(aes(colour = sex),
     size = 1,
     data = penguins_pcp %>% filter(sex == "?")
   ) +
   geom_pcp_labels(aes(label = pcp_level), alpha = .75) +
   scale_colour_manual("Sex", values = c("#FFCD70", "#8b4950", "#008080")) +
   theme_pcp() +
   theme(legend.position = "none") +
   scale_x_discrete(
     labels = c(
       "Species", "Bill Length (mm)", "Flipper Length (mm)",
       "Body Mass (g)", "- Bill Depth(mm)", "Species",
       "Sex"
     )
   )

penguins_pcp <- penguins %>%
  filter(species != "Chinstrap") %>% # no unsexed animals in Chinstrap
  mutate(                            # make assignment more readable
    sex = ifelse(is.na(sex),"?", as.character(sex)),
    sex = factor(sex, levels = c("female", "?", "male"))
  ) %>%
  filter(!is.na(body_mass_g)) %>%
  pcp_select(6:5, 3:4) %>%
  group_by(species) %>%              # re-scale by species
  pcp_scale() %>%
  pcp_arrange()


# making ribbons
probs <- c(0.025, 0.25, 0.75, 0.975)

dframe <-
  penguins_pcp %>%
  filter(sex != "?") %>%
  group_by(species, sex, pcp_x) %>%
  summarise(
    value = quantile(pcp_y, prob = probs),
    quantile = probs,
    lower = probs < 0.5,
    level = round(10 * abs(quantile - 0.5), digits = 1)
  ) %>%
  select(-quantile) %>%
  mutate(lower = factor(lower, labels = c("upper", "lower"))) %>%
  pivot_wider(names_from = "lower", values_from = "value") %>%
  ungroup() %>%
  mutate(
    level = ifelse(level > 2.5, "Inner 95%", "Inner 50%"),
    level = factor(level, levels = c("Inner 50%", "Inner 95%"))
  )

# for annotations
annotate_dframe <- penguins_pcp %>%
  filter(sex == "?", !is.na(body_mass_g), pcp_x == "body_mass_g")

library(emojifont)
load.fontawesome()
labels <- fontawesome(c("fa-venus", "fa-mars", "fa-question"))

annotate_dframe$putative <- labels[1]
annotate_dframe <- annotate_dframe %>% mutate(
  putative = ifelse(pcp_y > 0.4, labels[3], putative),
  putative = ifelse(pcp_y > 0.5, labels[2], putative)
)

circle <- c("", "")

# recalculate position by group
penguins_pcp %>%
  filter(sex != "?") %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp_boxes(boxwidth = 0.1) +
  geom_ribbon(aes(ymin = lower, ymax = upper, group = interaction(sex, level), fill = sex, alpha = level),
    data = dframe
  ) +
  geom_pcp(aes(colour = sex, fill = "?"),
    colour = "#8b4950dd", size = 0.9,
    data = penguins_pcp %>% filter(sex == "?") %>% mutate(sex = "female")
  ) +
  geom_pcp(aes(colour = sex, fill = "?"),
    colour = "#8b4950dd", size = 0.9,
    data = penguins_pcp %>% filter(sex == "?") %>% mutate(sex = "male")
  ) +
  geom_pcp_labels(aes(label = pcp_level), alpha = .5) +
  theme_bw() +
  scale_fill_manual(values = c("#8b4950", "#FAA404", "#008080")) +
  theme(legend.position = "bottom") +
  facet_grid(species ~ sex) +
  scale_x_discrete(expand = expansion(add = 0.25)) +
  xlab("") +
  ylab("") +
  scale_alpha_manual("Inter-quantile Range", values = c(0.25, 0.25)) +
  guides(
    fill = guide_legend(override.aes = list(alpha = 0.5)),
    alpha = guide_legend(override.aes = list(alpha = c(0.5, 0.25)))
  ) +
  geom_text(aes(colour = sex, label = putative),
    colour = "#8b4950",
    data = annotate_dframe %>% mutate(sex = "male"), nudge_x = -0.125,
    family = "fontawesome-webfont", size = 5
  ) +
  geom_text(aes(colour = sex, label = putative),
    colour = "#8b4950",
    data = annotate_dframe %>% mutate(sex = "female"), nudge_x = -0.125,
    family = "fontawesome-webfont", size = 5
  ) +
  geom_text(aes(label = marker),
    data = data.frame(
      species = "Adelie",
      marker = c("A", "A", "B", "B"),
      pcp_y = c(0.783, 0.433, 0.3, 0.267),
      pcp_x = "bill_depth_mm",
      nest = c("N5", "N5", "N6", "N6")
    ),
    colour = "#8b4950",
    nudge_x = 0.1, size = 3
  ) +
  theme_pcp() +
  scale_x_discrete(
    expand = expansion(add = 0.2),
    labels = c(
      "Body Mass (g)", "Flipper Length (mm)",
      "Bill Length (mm)", "Bill Depth (mm)"
    )
  )

data("carcinoma", package = "poLCA")
carcinoma$numdiag <- rowSums(carcinoma) - 7
carcinoma$any <- carcinoma$numdiag > 0

carcinoma[, 1:7] <- carcinoma[, 1:7] %>%
  purrr::map(.f = function(x) factor(x, labels = c("no", "yes"))) %>%
  data.frame()

carcinoma %>%
  pcp_select(6, 4, 3, 1, 7, 5, 2) %>%
  pcp_scale(method = "raw") %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp_boxes() +
  geom_pcp(aes(colour = factor(numdiag))) +
  geom_pcp_labels(aes(label = pcp_level), alpha = .5) +
  scale_colour_brewer("Number of\ncarcinoma\ndiagnoses", palette = "Dark2") +
  theme_bw() +
  guides(color = guide_legend(reverse = TRUE, override.aes = list(size = 3))) +
  scale_x_discrete(expand = expansion(add = 0.25)) +
  xlab("Pathologist") +
  ylab(NULL) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

data(Carcinoma, package = "ggpcp")
Carcinoma_pcp <- Carcinoma %>%
  mutate(
    `round(Average)` = factor(round(Average))
  ) %>%
  arrange(`round(Average)`) %>%
  pcp_select(F, D, C, A, G, E, B, `round(Average)`) %>%
  pcp_scale(method = "uniminmax") %>%
  pcp_arrange()

var_id <- Carcinoma_pcp %>%
  filter(pcp_x != "round(Average)") %>%
  group_by(pcp_id) %>%
  summarize(
    var_y = var(pcp_y),
    var_scores = var(parse_number(pcp_level))
  )

var_id <- var_id %>% left_join(
  Carcinoma_pcp %>% ungroup() %>%
    select(pcp_id, `round(Average)`) %>% unique(),
  by = "pcp_id"
)

var_id <- var_id %>% mutate(
  group = 4,
  group = ifelse((var_y > 0.02) & (var_scores < 1.25), 2, group),
  group = ifelse((var_y > 0.02) & (var_scores > 1.25), 1, group),
  group = ifelse(between(var_scores, 0.75, 1.25) & (var_y < 0.02), 3, group)
)

# https://coolors.co/045a8d-74a9cf-fdbe85-f03b20-bd0026
# scatterplot of variances against each other
ggvars <- var_id %>%
  ggplot(aes(x = var_y, y = var_scores)) +
  geom_point(aes(colour = `round(Average)`, alpha = var_y)) +
  geom_point(
    colour = "grey90",
    data = var_id %>% filter(var_y < 0.001)
  ) + # fudging a bit to grey out points with high frequencies
  xlab("Var(pcp_y)") +
  ylab("Var(scores)") +
  scale_color_manual(values = c("#045a8d", "#74a9cf", "#fdbe85", "#f03b20", "#bd0026")) +
  theme(legend.position = "none") +
  geom_point(aes(colour = `round(Average)`),
    data = var_id %>% filter(var_y > 0.02)
  )

Carcinoma_pcp %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp_boxes() +
  geom_pcp(aes(colour = `round(Average)`), overplot = "none") +
  geom_pcp(aes(colour = `round(Average)`),
    data = Carcinoma_pcp %>% filter(pcp_id %in% rev(c(115, 50, 53, 99, 96, 104, 97, 102, 114)))
  ) +
  geom_pcp_labels() +
  theme_bw() +
  scale_x_discrete(expand = expansion(add = c(0.2, 0.4))) +
  xlab("Pathologist") +
  ylab("Carcinoma score") +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  theme(legend.position = "none") +
  scale_colour_manual("Average carcinoma score", values = c("#045a8d", "#74a9cf", "#fdbe85", "#f03b20", "#bd0026")) +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(size = 2)))

Carcinoma_pcp2 <- Carcinoma_pcp %>%
  left_join(var_id %>% select(pcp_id, var_scores, var_y, group), by = "pcp_id")


hist <-
  var_id %>%
  mutate(
    var_low = var_y < 0.02,
    var_disc = ifelse(var_low, "Low", "High"),
    var_disc = factor(var_disc, levels = c("Low", "High"))
  ) %>%
  ggplot(aes(
    x = var_y, fill = `round(Average)`,
    alpha = var_disc
  )) +
  geom_histogram(binwidth = 0.01, colour = "grey50", size = 0.1) +
  scale_fill_manual("Average carcinoma score", values = c(
    "#045a8d", "#74a9cf", "#fdbe85", "#f03b20",
    "#bd0026"
  )) +
  xlab("Var(pcp_y)") +
  ylab("Number of scans") +
  scale_alpha_manual("Var(pcp_y)",
    values = c(0.25, 1)
  ) +
  theme(
    legend.position = "right",
    legend.direction = "horizontal"
  ) +
  guides(
    fill =
      guide_legend(
        title.position = "top",
        title.hjust = 0
      ),
    alpha = guide_legend(title.position = "top", title.hjust = 0)
  )


gpcp <- Carcinoma_pcp2 %>%
  ggplot(aes_pcp()) +
  geom_pcp_axes() +
  geom_pcp_boxes() +
  geom_pcp(aes(colour = `round(Average)`),
    overplot = "none",
    alpha = 0.15
  ) +
  geom_pcp(aes(colour = `round(Average)`),
    data = Carcinoma_pcp2 %>% filter(var_y > 0.02)
  ) +
  geom_pcp_labels() +
  theme_bw() +
  scale_x_discrete(expand = expansion(add = c(0.2, 0.4))) +
  xlab("Pathologist") +
  ylab("Carcinoma score") +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  theme(legend.position = "none") +
  scale_colour_manual(
    "Average carcinoma score",
    values = c("#045a8d", "#74a9cf", "#fdbe85", "#f03b20", "#bd0026")
  ) + # theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(size = 2)))

layout <- "
AAAAAAAAA
BBBBBCCCC
"
gpcp + hist + ggvars +
  plot_layout(design = layout, heights = c(1.5, 1))



penguins_complete <- penguins %>% na.omit()

# run kmeans for k from 2 to 8, sort clusters by body weight,
# then label clusters from lightest to heaviest
set.seed(20220901)

clusters <- tibble(k = 2:8)
clusters <- clusters %>% mutate(
  kmeans_cl = k %>% purrr::map(.f = function(cl) {
    kmeans(penguins_complete %>%
      dplyr::select(bill_length_mm:body_mass_g) %>%
      mutate(
        across(.fns = scale)
      ), centers = cl)
  })
)

penguins_complete$cl2 <- clusters$kmeans_cl[[1]]$cluster
penguins_complete$cl3 <- clusters$kmeans_cl[[2]]$cluster
penguins_complete$cl4 <- clusters$kmeans_cl[[3]]$cluster
penguins_complete$cl5 <- clusters$kmeans_cl[[4]]$cluster
penguins_complete$cl6 <- clusters$kmeans_cl[[5]]$cluster
penguins_complete$cl7 <- clusters$kmeans_cl[[6]]$cluster
penguins_complete$cl8 <- clusters$kmeans_cl[[7]]$cluster

penguins_complete <- penguins_complete %>% mutate(
  across(starts_with("cl"), as.factor),
  across(starts_with("cl"), .fns = function(cl) {
    cl <- reorder(cl, body_mass_g, mean)
    levels(cl) <- 1:length(levels(cl))
    cl
  })
)

penguins_complete %>%
  mutate(
    cl2 = reorder(cl2, body_mass_g, mean)
  ) %>%
  pcp_select(bill_length_mm:body_mass_g, cl2, species) %>%
  pcp_scale() %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp(aes(color = cl2), alpha = 0.6) +
  geom_pcp_boxes(fill = NA) +
  geom_pcp_labels() +
  theme_bw() +
  scale_color_manual(values = c(oranges[2], purples[2])) +
  theme(legend.position = "none") +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  scale_x_discrete("",
    expand = expansion(add = 0.25),
    labels = c(
      "Bill length", "Bill depth",
      "Flipper length", "Body mass",
      "k=2 Clusters", "Species"
    )
  ) +
  ggtitle("Clustering into 2 groups")


penguins_complete_pcp <- penguins_complete %>%
  mutate(
    cl3 = reorder(cl3, body_mass_g, mean)
  ) %>%
  pcp_select(bill_length_mm:body_mass_g, cl3, species) %>%
  pcp_scale() %>%
  pcp_arrange()

penguins_complete_pcp %>%
  ggplot(aes_pcp()) +
  geom_pcp(aes(color = cl3),
    alpha = 0.6,
    data = filter(penguins_complete_pcp, cl3 != "2")
  ) +
  geom_pcp(aes(color = cl3),
    alpha = 0.6,
    data = filter(penguins_complete_pcp, cl3 == "2")
  ) +
  geom_pcp_boxes(fill = NA) +
  geom_pcp_labels() +
  theme_bw() +
  scale_color_manual(values = c(oranges[2], greens[2], purples[2])) +
  theme(legend.position = "none") +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  scale_x_discrete("",
    expand = expansion(add = 0.25),
    labels = c(
      "Bill length", "Bill depth",
      "Flipper length", "Body mass",
      "k=3 Clusters", "Species"
    )
  ) +
  ggtitle("Clustering into 3 groups")



penguins_complete %>%
  mutate(
    cl4 = reorder(cl4, body_mass_g, mean)
  ) %>%
  pcp_select(bill_length_mm:body_mass_g, cl4, species, sex) %>%
  pcp_scale() %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp(aes(color = cl4), alpha = 0.6) +
  geom_pcp_boxes(fill = NA) +
  geom_pcp_labels() +
  theme_bw() +
  scale_color_manual(values = c(oranges[1], greens[2], oranges[3], purples[2])) +
  theme(legend.position = "none") +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  scale_x_discrete("",
    expand = expansion(add = 0.25),
    labels = c(
      "Bill length", "Bill depth",
      "Flipper length", "Body mass",
      "k=4 Clusters", "Species"
    )
  ) +
  ggtitle("Clustering into 4 groups")


penguins_complete_pcp <- penguins_complete %>%
  mutate(
    cl5 = reorder(cl5, body_mass_g, mean)
  ) %>%
  pcp_select(bill_length_mm:body_mass_g, cl5, species, sex) %>%
  pcp_scale() %>%
  pcp_arrange()

penguins_complete_pcp %>%
  ggplot(aes_pcp()) +
  geom_pcp(aes(color = cl5),
    alpha = 0.6,
    data = filter(
      penguins_complete_pcp,
      species != "Chinstrap"
    )
  ) +
  geom_pcp(aes(color = cl5),
    alpha = 0.6,
    data = filter(
      penguins_complete_pcp,
      species == "Chinstrap"
    )
  ) +
  geom_pcp_boxes(fill = NA) +
  geom_pcp_labels() +
  theme_bw() +
  scale_color_manual(
    values = c(oranges[1], greens[1], greens[3], oranges[3], purples[2])
  ) +
  theme(legend.position = "none") +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  scale_x_discrete("",
    expand = expansion(add = 0.25),
    labels = c(
      "Bill length", "Bill depth",
      "Flipper length", "Body mass",
      "k=5 Clusters", "Species"
    )
  ) +
  ggtitle("Clustering into 5 groups")

penguins_complete_pcp <- penguins_complete %>%
  mutate(
    cl6 = reorder(cl6, body_mass_g, mean)
  ) %>%
  pcp_select(bill_length_mm:body_mass_g, cl6, species, sex) %>%
  pcp_scale() %>%
  pcp_arrange()

penguins_complete_pcp %>%
  ggplot(aes_pcp()) +
  geom_pcp(aes(color = cl6),
    alpha = 0.6,
    data = filter(penguins_complete_pcp, species != "Gentoo")
  ) +
  geom_pcp(aes(color = cl6),
    alpha = 0.6,
    data = filter(penguins_complete_pcp, species == "Gentoo")
  ) +
  geom_pcp_boxes(fill = NA) +
  geom_pcp_labels() +
  theme_bw() +
  #  scale_color_brewer(type="qual") +
  scale_color_manual(values = c(oranges[1], greens[2], oranges[2], oranges[3], purples[1], purples[3])) +
  theme(legend.position = "none") +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(
    labels = c("low", "", "medium", "", "high"),
    breaks = c(0, 0.25, .5, .75, 1)
  ) +
  scale_x_discrete("",
    expand = expansion(add = 0.25),
    labels = c(
      "Bill length", "Bill depth",
      "Flipper length", "Body mass",
      "k=6 Clusters", "Species"
    )
  ) +
  ggtitle("Clustering into 6 groups")

set.seed(20220901)
clusters6 <- tibble(k = rep(6, 7))
clusters6 <- clusters6 %>% mutate(
  kmeans_cl = k %>% purrr::map(.f = function(cl) {
    kmeans(penguins_complete %>%
      select(bill_length_mm:body_mass_g) %>%
      mutate(
        across(.fns = scale)
      ), centers = cl)
  })
)

penguins_complete$cl6b <- clusters6$kmeans_cl[[1]]$cluster
penguins_complete$cl6c <- clusters6$kmeans_cl[[2]]$cluster
penguins_complete$cl6d <- clusters6$kmeans_cl[[3]]$cluster
penguins_complete$cl6e <- clusters6$kmeans_cl[[4]]$cluster
penguins_complete$cl6f <- clusters6$kmeans_cl[[5]]$cluster
penguins_complete$cl6g <- clusters6$kmeans_cl[[6]]$cluster
penguins_complete$cl6h <- clusters6$kmeans_cl[[7]]$cluster

penguins_complete <- penguins_complete %>% mutate(
  across(starts_with("cl6"), as.factor),
  across(starts_with("cl6"), .fns = function(cl) {
    cl <- reorder(cl, as.numeric(species:sex), mean)
    levels(cl) <- 1:length(levels(cl))
    cl
  })
)

penguins_complete %>%
  pcp_select(starts_with("cl6"), species, sex) %>%
  pcp_scale() %>%
  pcp_arrange() %>%
  ggplot(aes_pcp()) +
  geom_pcp(aes(color = interaction(sex, species)), alpha = 0.6) +
  geom_pcp_boxes(fill = NA, colour = "black", size = .5) +
  geom_pcp_labels(alpha = 0.9) +
  theme_bw() +
  scale_color_manual(values = c(greens[c(1, 3)], oranges[c(1, 3)], purples[c(1, 3)])) +
  theme(legend.position = "none") +
  ylab("") +
  theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
  scale_y_continuous(breaks = NULL) +
  scale_x_discrete("", expand = expansion(add = 0.5))


## penguins_complete %>%
##   mutate(
##     across(starts_with("cl"), .fns = function(x) reorder(x, body_mass_g, mean))
##   ) %>%
##   select(-c(cl7, cl8)) %>%
##   pcp_select(starts_with("cl"), species, sex) %>%
##   pcp_scale() %>%
##   pcp_arrange(space = 0.1) %>%
##   ggplot(aes_pcp()) +
##   geom_pcp(aes(color = interaction(sex, species)), alpha = 0.6, axiswidth = c(0, 0.1)) +
##   geom_pcp_boxes(fill = NA) +
##   geom_pcp_labels() +
##   theme_bw() +
##   scale_color_manual(values = c(purples[1], purples[3], oranges[1], oranges[3], greens[1], greens[3])) +
##   theme(legend.position = "none") +
##   ylab("") +
##   theme(axis.title.y = NULL, axis.text.y = NULL, axis.ticks.y = NULL) +
##   scale_y_continuous(breaks = NULL) +
##   scale_x_discrete("", expand = expansion(add = 0.25))
## 
